[server]
host = "0.0.0.0"
port = 8080
production = false
cors-url = ["*"]

[server.security]
jwt-secret = "somethingxyz"
token-expiry = "6h"

[database]
host = "db.mhxubnxliyyrsqhgtsac.supabase.co"
port = 5432
username = "postgres"
password = "moggy@1234$$"
db-name = "postgres"
ssl-mode = "disable"
max-tries = 5

[app]
temp-dir-path = "./temp"
gemini-api-key = "better-luck-next-time"
