[server]
host = "0.0.0.0"
port = 8080
production = false

[server.security]
jwt-secret = "somethingxyz"
token-expiry = "6h"

[database]
host = "database"
port = 5432
username = "test"
password = "test"
db-name = "test"
ssl-mode = "disable"
max-tries = 5

[app]
gemini-api-key = "better-luck-next-time"
